if [ -f $HOME/.Xdefaults ]; then
	xrdb -merge $HOME/.Xdefaults
fi
if [ -f /etc/X11/xinit/xinitrc-common ]; then
	. /etc/X11/xinit/xinitrc-common
fi
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session ~/.startdwm
