#!/bin/bash

while read line; do
	yum erase -y "$line"
done << EOF
smolt*
iok
empathy
evolution
gnumeric
goffice
EOF

yum update -y

while read line; do
	yum install -y "$line"
done <<EOF
vim-enhanced
vim-X11
libxml2
libxml2-devel
libxslt
libxslt-devel
krb5-workstation
rxvt-unicode
git
python-devel
python-pygments
python-docutils
xfce4-power-manager
gvfs
gvfs-smb
acpi
Thunar
thunar-volman
gnome-keyring
ruby
ruby-devel
ruby-irb
ruby-libs
rubygems
w3m
curl
wget
powertop
htmldoc
ImageMagick
ImageMagick-devel
fontmatrix
libX11-devel
libXinerama-devel
keepassx
xlockmore
wmname
gimp
dia
inkscape
graphviz
optipng
terminus-fonts
terminus-fonts-console
liberation-*
dejavu-*
aajohan-comfortaa-fonts
abattis-cantarell-fonts
libreoffice-writer
libreoffice-draw
libreoffice-impress
libreoffice-graphicfilter
libreoffice-langpack-en
xchat
audit
audit-libs-devel
redhat-lsb
libXScrnSaver
gnupg
gnupg2
thunderbird
lua
lua-devel
luarocks
docbook5-*
fop
jing
EOF

yum groupinstall -y 'Development Tools'

systemctl disable iscsi.service
systemctl disable iscsid.service
systemctl disable atd.service
systemctl disable cron.service
systemctl disable abrt.service
systemctl disable bluetooth.service
systemctl disable lvm2-monitor.service
systemctl disable avahi-daemon.service
systemctl disable mdmonitor-takeover.service
systemctl disable sendmail.service
systemctl disable NetworkManager.service

# Install misc codec support

yum --nogpgcheck -y install http://rpm.livna.org/livna-release.rpm http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm
yum install -y totem-mozplugin gstreamer-plugins-ugly gstreamer-plugins-bad gstreamer-ffmpeg libdvdcss libdvdnav

# Install Google chrome
# Needed for google-chrome package
# yum install -y redhat-lsb libXScrnSaver

echo "yum install complete..."
echo "Oracle Java, google-chrome, and flash packages must be manually installed"

