# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
set -o vi

alias chrome="google-chrome --incognito"
# alias ll='ls -l'
# alias la='ls -la'
alias vi='gvim -v'
alias df='df -h'
alias w3m='w3m -T text/html'
# alias xm='xmodmap $HOME/.Xmodmap'
alias bc='bc -l'
alias pdf='epdfview'

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

alias encrypt='openssl enc -aes-256-ecb -e -a -salt -in'
alias decrypt='openssl enc -aes-256-ecb -d -a -salt -in'

