# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
set -o vi

alias chrome="google-chrome --incognito"
# alias ll='ls -l'
# alias la='ls -la'
alias vi='gvim -v'
alias df='df -h'
alias w3m='w3m -T text/html'
# alias xm='xmodmap $HOME/.Xmodmap'
alias bc='bc -l'
alias pdf='epdfview'
alias pip='pip-python'
alias pip-install='pip-python install --install-option="--user"'

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:$HOME/.local/bin
export PATH
export VISUAL=vim
export EDITOR=vim
export XMLLINT_INDENT="    "
export PYTHONPATH=`python -c 'import sys;print ":".join(sys.path[2:])'`
export JYTHONPATH=$PYTHONPATH

alias encrypt='openssl enc -aes-256-ecb -e -a -salt -in'
alias decrypt='openssl enc -aes-256-ecb -d -a -salt -in'

alias dbkvalidate='xmllint --stream --noout --relaxng /usr/share/xml/docbook5/schema/rng/5.0/docbook.rng'
alias dbk2html='xsltproc -xinclude -o out.html /usr/share/sgml/docbook/xsl-ns-stylesheets/html/docbook.xsl'

# Setup python virtualenv

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Documents/devel
source $HOME/.local/bin/virtualenvwrapper.sh

